### ISSUE TITLE
shaderc segfaults when using more than one include path

### ISSUE THREAD

**Issue by samloeschen** [cyberegoorg/zbgfx#1]
Currently, shaderc segfaults during shader compilation when `ShadercOptions.includeDirs` has a length greater than 1. I've made a [simple repro project](https://github.com/samloeschen/shaderc-repro) demonstrating the error. Strangely, I cannot get it to happen if I add more paths to the 02-runtime-shaderc example, but the bgfx state should be the same in the repro as far as I can tell.

To reproduce: 
-> clone the repro project: [https://github.com/samloeschen/shaderc-repro](/url)
-> cd into project folder and `zig build run`
-> shaderc should segfault during shader compilation

shaderc will succeed if you simply delete the second array element at L85 of main.zig.

Apologies if this error is on my end! I'm definitely still learning zig and bgfx, so could have overlooked something. 

Environment:
M2 Air, MacOS 14.3.1

**Comment by samloeschen** [comment]
should be fixed by https://github.com/cyberegoorg/zbgfx/pull/2#issue-2393577069

**Comment by OndraVoves** [comment]
Nice catch 😄
